# (i) Location line with first instance of series name and the States using it (FIPS code)
# (ii) Status of soil series (tentative, established, or inactive)
# (iii) Initials of authors
# (iv) Date of latest revision (autogenerated in mm/yyyy format)
# (v) Name of soil series
# (vi) Introductory paragraph
# (vii) Taxonomic class
# (viii) Typical pedon
# (ix) Type location
# (x) Range in characteristics
# (xi) Competing series
# (xii) Geographic setting
# (xiii) Geographically associated soils
# (xiv) Drainage and saturated hydraulic conductivity (permeability in older series)
# (xv) Use and vegetation
# (xvi) Distribution and extent
# (xvii) SSR responsible
# (xviii) Series proposed or series established
# (xix) Remarks on diagnostic horizons 
# 
# The guidelines for keying soil series descriptions are as follows:
#   -- Left margin is in column 1. Right margin is in column 66.
# -- Tabs, stop codes, required hyphen codes, required backspace codes, automatic centering, and
# underlines are not used. The spacebar is used instead of tabs.
# -- Everything is left justified. The horizon designations do not need to be indented.
# -- Section headings are in capital letters, for example, TAXONOMIC CLASS and TYPICAL
# PEDON, and followed by a colon (:). Do not begin any line, other than the section headings, with
# words or abbreviations in capital letters plus a colon. The validation of descriptions with the
# SC/OSD Maintenance Tool will return error messages for unexpected headings unless attention is
# given to proper format.
# -- Depths and thickness (cm), temperature (whole degrees C), precipitation (mm), and elevation
# (meters) are in metric units of measure; acreage and legal descriptions (longitude and latitude in
#                                                                          degrees, minutes, and seconds with WGS84 as horizontal datum are preferred) are in English
# units. General locations can be given in feet and miles.
# -- Special symbols, subscripts, and superscripts must be expressed as words. (For example: 10° is
#                                                                               changed to 10 degrees, CaCO3 is changed to calcium carbonate, and 10% is changed to 10 percent.)
# -- The first 8 lines and the last line of the soil series description must be standardized in order for the
# validations of the SC/OSD maintenance tool to work. All entries are left justified and start in
# column 1.
# 
# Line l--LOCATION GAMMA NE (This line is entered in capital letters. The first letter of
#                            the State where the soil series is located must be in the 33rd character location starting from the leftmost side
#                            at the first character location. If other States are using the series, the first letter of the other State must be in
#                            the 36th character location. Any other States using the series follow in alphabetical order.)
# Line 2--Blank line
# Line 3--Tentative Series or Established Series (Note: Even series with inactive status are shown as such
#                                                 on this line.)
# Line 4--Rev. MLD-JRC [These are the initials of the individuals who last revised the soil series. The
#                       initials are separated by a hyphen (-), a slash (/), or a comma (,).]
# Line 5--08/2012 (This is the two-digit month and four-digit year in which the official soil series
#                  description was last revised in the soil series classification database or in the official series description file
#                  share. The system enters this date automatically.)
# Line 6--Blank line
# Line 7--GAMMA SERIES (All letters are capped.)
# Line 8--Blank line
# Line 8 is followed by the introductory paragraph and the rest of the soil series description.
# Next to last line--National Cooperative Soil Survey
# Last line--U.S.A. (All letters are capped and do not have spaces inbetween.)
# The completed description must be run through a spell checker in word-processing software
