name: Refresh Official Series Descriptions

# just for testing
on: push

# eventually, refresh will only occur on scheduled interval
# on:
#  schedule:
##  e.g. weekly cycle
#    - cron:  '* * * * */6'
##  e.g. every 15 minutes
#    - cron:  '*/15 * * * *'
defaults:

# see: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# and: https://github.com/r-lib/actions
jobs:
  refresh-osd:
    runs-on: ubuntu-latest
    
    steps:
    - run: sudo add-apt-repository -y ppa:cran/poppler
    - run: sudo apt-get update
    - run: sudo apt install libcurl4-openssl-dev libpoppler-cpp-dev
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - run: Rscript -e 'install.packages(c("remotes", "rcmdcheck"))'
    - run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'
    - run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
    - run: R CMD build --no-manual ../OSDRegistry
    - run: Rscript -e 'system2("R", paste0(sprintf("CMD INSTALL OSDRegistry_%s.tar.gz", read.dcf("DESCRIPTION")[,"Version"])))'
    - run: Rscript inst/refresh.R
    - run: git config --global user.email "andrew.g.brown@usda.gov"
    - run: git config --global user.name "Andrew G. Brown"
    - run: git add OSD/*
    - run: Rscript -e 'system(sprintf("git commit -am \"OSD Data Refresh - %s\"", Sys.time()))'
    - run: git push https://${{github.actor}}:${{secrets.GH_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
    - run: Rscript {0}
env:
  DEFAULT_BRANCH: main
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
