name: refresh-osd

# just for testing
#on: push

# weekly refresh Midnight (0:00 UTC) on Mondays
on:
 schedule:
 - cron:  '0 0 * * 1'

 workflow_dispatch:

# see: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# and: https://github.com/r-lib/actions
jobs:
  refresh:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update
    - run: sudo apt install -y libcurl4-openssl-dev chromium-chromedriver firefox
    # - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    # - run: sudo apt install ./google-chrome-stable_current_amd64.deb
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: ncss-tech/soilDB
    - run: R CMD build --no-manual ../OSDRegistry
    - run: Rscript -e 'system2("R", paste0(sprintf("CMD INSTALL OSDRegistry_%s.tar.gz", read.dcf("DESCRIPTION")[,"Version"])))'
    - run: Rscript -e 'OSDRegistry::refresh_registry()'
    - run: Rscript -e 'system(sprintf("zip OSD_%s.zip OSD/*/*", Sys.Date()))'
    - run: Rscript -e 'system(sprintf("zip SC_%s.zip SC/*", Sys.Date()))'
    - run: zip OSD-data-snapshot.zip OSD_*.zip
    - run: zip SC-data-snapshot.zip SC_*.zip
    - uses: actions/upload-artifact@v3
      with:
        name: OSD-data-snapshot
        path: "OSD-data-snapshot.zip"
    - uses: actions/upload-artifact@v3
      with:
        name: SC-data-snapshot
        path: "SC-data-snapshot.zip"
    - run: git config user.email github-actions@github.com
    - run: git config user.name SeriesCuratorBot
    - run: git add OSD/*/*.txt
    - run: Rscript -e 'system(sprintf("git commit -am \"OSD Data Refresh - %s\"", Sys.Date()))'
    - run: git add SC/*
    - run: Rscript -e 'system(sprintf("git commit -am \"SC Data Refresh - %s\"", Sys.Date()))'
    - run: git push
    - name: Upload snapshot to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "*-data-snapshot.zip"
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
        body: "Download the complete Official Series Description and Series Classification Database weekly snapshot as ZIP files."
env:
  DEFAULT_BRANCH: main
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
